const car = {
  toyota: {
    suv: 'Fortuner',
    coupe: '86',
    minivan: 'Sienna',
    van: 'Hiace',
    sedan: 'Camry',
    hatchback: 'Yaris',
    pickup: 'Hilux',
    offRoad: 'Land Cruiser',
  },
  hyundai: {
    suv: 'Tucson',
    coupe: 'Veloster',
    minivan: 'Staria',
    van: 'H-1',
    sedan: 'Sonata',
    hatchback: 'i30',
    pickup: 'Santa Cruz',
    offRoad: '',
  },
  ford: {
    suv: 'Explorer',
    coupe: 'Mustang',
    minivan: '',
    van: 'Transit',
    sedan: 'Fusion',
    hatchback: 'Focus',
    pickup: 'Ranger',
    offRoad: 'Bronco',
  },
  honda: {
    suv: 'CR-V',
    coupe: 'Civic Coupe',
    minivan: 'Odyssey',
    van: '',
    sedan: 'Accord',
    hatchback: 'Civic Hatchback',
    pickup: 'Ridgeline',
    offRoad: '',
  },
  nissan: {
    suv: 'X-Trail',
    coupe: '370Z',
    minivan: 'Serena',
    van: 'NV350',
    sedan: 'Altima',
    hatchback: 'Leaf',
    pickup: 'Navara',
    offRoad: 'Patrol',
  },
};

console.log(car);
